# Modelo con Regresion Logistica

## Importar librerías

In [169]:
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns 
import numpy as np 
#from sklearn.linear_model import LogisticRegression
#from sklearn.model_selection import train_test_split
#from sklearn.metrics import confusion_matrix
import tensorflow as tf
from tensorflow import keras
import tensorflow as tf
from tensorflow import keras
from sklearn.metrics import mean_squared_error

## Carga de datos

In [170]:
df = pd.read_csv('datoslimpios.csv')

## filtado de variables numericas

In [171]:
# Eliminar la variable 'date' del DataFrame
df = df.drop(columns=['wip'])
df = df.drop(columns=['date'])

# Filtrar solo variables numéricas
df_numeric = df.select_dtypes(include='number')

# División de los datos en características (X) y etiquetas (y)
x = df_numeric.drop(columns=['actual_productivity'])  
y = df_numeric['actual_productivity']

## Split de datos en train y test

In [172]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [173]:
x_train

,Unnamed: 0,team,targeted_productivity,smv,over_time,incentive,idle_time,idle_men,no_of_style_change,no_of_workers
361,361,5,0.70,20.40,10440,50,0.0,0,0,58.0
619,619,1,0.80,22.52,6900,113,0.0,0,0,57.5
494,494,6,0.35,18.79,1800,23,0.0,0,0,32.0
695,695,1,0.80,22.52,0,88,0.0,0,0,57.0
395,395,8,0.80,2.90,1620,0,0.0,0,0,9.0
...,...,...,...,...,...,...,...,...,...,...
1033,1033,8,0.75,29.40,6840,56,0.0,0,0,57.0
763,763,3,0.50,30.10,6960,30,0.0,0,1,58.0
835,835,9,0.70,18.79,4560,30,0.0,0,1,51.0
559,559,7,0.70,24.26,6720,0,0.0,0,0,56.0
684,684,11,0.75,10.05,0,45,0.0,0,0,54.0

## Entrenamiento de modelo

In [174]:
x_train.dtypes

Unnamed: 0                 int64
team                       int64
targeted_productivity    float64
smv                      float64
over_time                  int64
incentive                  int64
idle_time                float64
idle_men                   int64
no_of_style_change         int64
no_of_workers            float64
dtype: object

In [177]:
import tensorflow as tf
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

def build_model(input_shape):
    model = tf.keras.Sequential([
        tf.keras.layers.Input(shape=input_shape),
        tf.keras.layers.Dense(64, activation='relu'),
        tf.keras.layers.Dense(1, activation='sigmoid')  # Capa de salida para regresión logística
    ])
    return model


def train_neural_network(X_train, y_train, epochs=10, batch_size=32):
    # Normalizar características
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    
    # Construir el modelo
    input_shape = X_train_scaled.shape[1:]
    model = build_model(input_shape)
    
    # Compilar el modelo
    model.compile(optimizer='adam',
                  loss='mean_squared_error',  # Binary crossentropy para regresión logística
                  metrics=['mean_squared_error'])  # Métrica de precisión
    
    # Entrenar el modelo
    model.fit(X_train_scaled, y_train, epochs=epochs, batch_size=batch_size)

    return model


# Ejemplo de uso
# Suponiendo que tienes X_train y y_train
model = train_neural_network(x_train, y_train)

# Entrenar el modelo con las variables categóricas incluidas
#model_encoded = train_neural_network(x_train, y_train)

Epoch 1/10
30/30 [==============================] - 1s 2ms/step - loss: 0.0583 - mean_squared_error: 0.0583
Epoch 2/10
30/30 [==============================] - 0s 2ms/step - loss: 0.0284 - mean_squared_error: 0.0284
Epoch 3/10
30/30 [==============================] - 0s 2ms/step - loss: 0.0236 - mean_squared_error: 0.0236
Epoch 4/10
30/30 [==============================] - 0s 2ms/step - loss: 0.0218 - mean_squared_error: 0.0218
Epoch 5/10
30/30 [==============================] - 0s 2ms/step - loss: 0.0208 - mean_squared_error: 0.0208
Epoch 6/10
30/30 [==============================] - 0s 2ms/step - loss: 0.0200 - mean_squared_error: 0.0200
Epoch 7/10
30/30 [==============================] - 0s 2ms/step - loss: 0.0195 - mean_squared_error: 0.0195
Epoch 8/10
30/30 [==============================] - 0s 2ms/step - loss: 0.0190 - mean_squared_error: 0.0190
Epoch 9/10
30/30 [==============================] - 0s 2ms/step - loss: 0.0187 - mean_squared_error: 0.0187
Epoch 10/10
30/30 [==============================] - 0s 2ms/step - loss: 0.0184 - mean_squared_error: 0.0184

## Evaluación del modelo

In [178]:
model.evaluate(x_test, y_test)

8/8 [==============================] - 0s 2ms/step - loss: 0.1031 - mean_squared_error: 0.1031

[0.10313737392425537, 0.10313737392425537]

## Carga de datos

In [206]:
df = pd.read_csv('datoslimpios.csv')

## filtado de variables numericas y categoricas

In [207]:
# Eliminar la variable 'date' del DataFrame
df = df.drop(columns=['wip'])
df = df.drop(columns=['date'])

# Codificación one-hot de las variables categóricas
df_encoded = pd.get_dummies(df, columns=['quarter', 'department', 'day'])

# División de los datos en características (X) y etiquetas (y)
x_encoded = df_encoded.drop(columns=['actual_productivity'])  
y_encoded = df_encoded['actual_productivity']

## Split de datos en train y test

In [208]:
# División de los datos en conjuntos de entrenamiento y prueba
x_train, x_test, y_train, y_test= train_test_split(x_encoded, y_encoded, test_size=0.2, random_state=0)

In [209]:
x_train

,Unnamed: 0,team,targeted_productivity,smv,over_time,incentive,idle_time,idle_men,no_of_style_change,no_of_workers,...,quarter_Quarter5,department_finishing,department_finishing,department_sweing,day_Monday,day_Saturday,day_Sunday,day_Thursday,day_Tuesday,day_Wednesday
361,361,5,0.70,20.40,10440,50,0.0,0,0,58.0,...,False,False,False,True,False,False,False,False,False,True
619,619,1,0.80,22.52,6900,113,0.0,0,0,57.5,...,False,False,False,True,False,False,False,True,False,False
494,494,6,0.35,18.79,1800,23,0.0,0,0,32.0,...,False,False,False,True,False,False,False,False,False,True
695,695,1,0.80,22.52,0,88,0.0,0,0,57.0,...,False,False,False,True,False,False,False,False,True,False
395,395,8,0.80,2.90,1620,0,0.0,0,0,9.0,...,False,False,True,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1033,1033,8,0.75,29.40,6840,56,0.0,0,0,57.0,...,False,False,False,True,False,False,False,False,True,False
763,763,3,0.50,30.10,6960,30,0.0,0,1,58.0,...,False,False,False,True,False,True,False,False,False,False
835,835,9,0.70,18.79,4560,30,0.0,0,1,51.0,...,False,False,False,True,False,False,False,False,False,True
559,559,7,0.70,24.26,6720,0,0.0,0,0,56.0,...,False,False,False,True,False,False,True,False,False,False
684,684,11,0.75,10.05,0,45,0.0,0,0,54.0,...,False,False,False,True,True,False,False,False,False,False

## Entrenamiento de modelo

In [210]:
x_train.dtypes

Unnamed: 0                 int64
team                       int64
targeted_productivity    float64
smv                      float64
over_time                  int64
incentive                  int64
idle_time                float64
idle_men                   int64
no_of_style_change         int64
no_of_workers            float64
quarter_Quarter1            bool
quarter_Quarter2            bool
quarter_Quarter3            bool
quarter_Quarter4            bool
quarter_Quarter5            bool
department_finishing        bool
department_finishing        bool
department_sweing           bool
day_Monday                  bool
day_Saturday                bool
day_Sunday                  bool
day_Thursday                bool
day_Tuesday                 bool
day_Wednesday               bool
dtype: object

In [211]:
import tensorflow as tf
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

def build_model(input_shape):
    model = tf.keras.Sequential([
        tf.keras.layers.Input(shape=input_shape),
        tf.keras.layers.Dense(64, activation='relu'),
        tf.keras.layers.Dense(1, activation='sigmoid')  # Capa de salida para regresión logística
    ])
    return model


def train_neural_network(X_train, y_train, epochs=10, batch_size=32):
    # Normalizar características
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    
    # Construir el modelo
    input_shape = X_train_scaled.shape[1:]
    model = build_model(input_shape)
    
    # Compilar el modelo
    model.compile(optimizer='adam',
                  loss='mean_squared_error',  # Binary crossentropy para regresión logística
                  metrics=['mean_squared_error'])  # Métrica de precisión
    
    # Entrenar el modelo
    model.fit(X_train_scaled, y_train, epochs=epochs, batch_size=batch_size)

    return model


# Ejemplo de uso
# Suponiendo que tienes X_train y y_train
model = train_neural_network(x_train, y_train)

# Entrenar el modelo con las variables categóricas incluidas
#model_encoded = train_neural_network(x_train, y_train)

Epoch 1/10
30/30 [==============================] - 1s 3ms/step - loss: 0.1032 - mean_squared_error: 0.1032
Epoch 2/10
30/30 [==============================] - 0s 3ms/step - loss: 0.0380 - mean_squared_error: 0.0380
Epoch 3/10
30/30 [==============================] - 0s 3ms/step - loss: 0.0274 - mean_squared_error: 0.0274
Epoch 4/10
30/30 [==============================] - 0s 2ms/step - loss: 0.0245 - mean_squared_error: 0.0245
Epoch 5/10
30/30 [==============================] - 0s 2ms/step - loss: 0.0231 - mean_squared_error: 0.0231
Epoch 6/10
30/30 [==============================] - 0s 2ms/step - loss: 0.0217 - mean_squared_error: 0.0217
Epoch 7/10
30/30 [==============================] - 0s 2ms/step - loss: 0.0209 - mean_squared_error: 0.0209
Epoch 8/10
30/30 [==============================] - 0s 2ms/step - loss: 0.0201 - mean_squared_error: 0.0201
Epoch 9/10
30/30 [==============================] - 0s 2ms/step - loss: 0.0195 - mean_squared_error: 0.0195
Epoch 10/10
30/30 [==============================] - 0s 2ms/step - loss: 0.0189 - mean_squared_error: 0.0189

## Evaluación del modelo

In [217]:
# Convert test data to float type
x_test = x_test.astype(float)
y_test = y_test.astype(float)

# Convert test data to tensors
x_test_tensor = tf.convert_to_tensor(x_test)
y_test_tensor = tf.convert_to_tensor(y_test)

# Evaluate the model
model.evaluate(x_test_tensor, y_test_tensor)

8/8 [==============================] - 0s 1ms/step - loss: 0.1387 - mean_squared_error: 0.1387

[0.13873879611492157, 0.13873879611492157]